# Generated by Django 2.0.4 on 2018-05-20 11:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('osm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='address_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')])),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_auth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_name', models.CharField(max_length=15)),
                ('feedback_email', models.EmailField(max_length=254)),
                ('feedback_type', models.CharField(max_length=15)),
                ('feedback_desc', models.TextField()),
                ('feedback_auth_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm.address_info')),
                ('order_auth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_payment_method', models.CharField(max_length=15)),
                ('order_quantity', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('order_total_payment', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{1,20}$')])),
                ('order_delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('product_price', models.CharField(max_length=15)),
                ('product_desc', models.TextField()),
                ('product_quantity', models.CharField(max_length=10)),
                ('product_brand', models.CharField(max_length=15)),
                ('product_add_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='product_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.FileField(upload_to='')),
                ('gallery_type', models.CharField(max_length=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm.product')),
            ],
        ),
        migrations.CreateModel(
            name='product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_name', models.CharField(max_length=20)),
                ('product_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm.product_category')),
            ],
        ),
        migrations.CreateModel(
            name='seller_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('bank_acc_no', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('seller_shop_name', models.CharField(max_length=40)),
                ('seller_auth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='seller_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm.seller_info')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm.product_type'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm.seller_product'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm.order_info'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm.product'),
        ),
    ]
