# Generated by Django 2.0.4 on 2018-05-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0003_auto_20180522_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm.seller_info'),
        ),
    ]
