# Generated by Django 2.0.4 on 2018-05-23 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0004_auto_20180522_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_info',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$')]),
        ),
    ]
