# Generated by Django 2.0.4 on 2018-05-24 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0005_auto_20180523_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_info',
            name='seller_shop_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seller_info',
            name='seller_shop_city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seller_info',
            name='seller_shop_pincode',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='seller_info',
            name='seller_shop_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
