# Generated by Django 2.0.4 on 2018-05-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0006_auto_20180524_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='order_quantity',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='order_total_payment',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(max_length=10),
        ),
    ]
