# Generated by Django 2.0.4 on 2018-05-24 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0008_auto_20180524_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_quantity',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator('^\\d[0-9]*$')]),
        ),
        migrations.AddField(
            model_name='cart',
            name='check',
            field=models.BooleanField(default=True, verbose_name='Check'),
        ),
    ]
