# Generated by Django 2.0.4 on 2018-05-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0009_auto_20180524_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='check',
            field=models.BooleanField(default=True, verbose_name='avilable'),
        ),
    ]
