# Generated by Django 2.0.4 on 2018-05-24 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0010_auto_20180524_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.RegexValidator('^\\d[0-9]*$')]),
        ),
    ]
