# Generated by Django 2.2.5 on 2019-10-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_type',
            name='product_type_name',
            field=models.CharField(max_length=30),
        ),
    ]
