# Generated by Django 2.2.5 on 2019-10-02 17:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='seller_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('bank_acc_no', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('seller_shop_name', models.CharField(max_length=40, null=True)),
                ('seller_shop_address', models.TextField(null=True)),
                ('seller_shop_city', models.CharField(max_length=20, null=True)),
                ('seller_shop_pincode', models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$')])),
                ('seller_auth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
